### ISSUE TITLE
Have you experienced the streamlit app becomes unresponsive?

### ISSUE THREAD

**Issue by MarcSkovMadsen** [virusvn/streamlit-components-demo#1]
Hi

I've visited your app https://fullstackstation.com/streamlit-components-demo a few times. The first time it was very responsive. But later it was not very responsive. Response times > 20 seconds. Now it seems responsive again.

I have the app 

https://awesome-streamlit.org/ running. 

It's ok responsive when just deployed but after 30 minutes to an hour the response times are low, i.e. more than 20 seconds. I have deployed as Azure Web Services for containers.

I just wondered if you had any experiences with this or thoughts because I really have tried everything possible to solve it.

I'm tracking the issue here https://github.com/streamlit/streamlit/issues/367

Any comments/ suggestions are appriciated. Thanks.

Marc

**Comment by virusvn** [comment]
I answered in https://github.com/streamlit/streamlit/issues/367
Thank for awesome-streamlit!
